name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Ensure the server starts
      env:
        PORT: 3000
      run: |
        npm start &
        for i in {1..10}; do
          curl -I http://localhost:3000 && break
          echo "Waiting for the server to start..."
          sleep 1
        done
